import * as github from '@actions/github';

interface ScanResult {
  files: Array<{
    file: string;
    diagnostics: Array<{
      ruleId: string;
      ruleName: string;
      severity: string;
      message: string;
      line: number;
    }>;
  }>;
  summary: {
    totalFiles: number;
    errorCount: number;
    warningCount: number;
    infoCount: number;
  };
  score: {
    score: number;
    grade: string;
  };
}

export async function postComment(result: ScanResult, token: string): Promise<void> {
  const octokit = github.getOctokit(token);
  const { owner, repo } = github.context.repo;
  const prNumber = github.context.payload.pull_request?.number;
  if (!prNumber) return;

  const { summary, score } = result;
  const gradeEmoji: Record<string, string> = {
    clean: '✅', low: '🟢', moderate: '🟡', high: '🟠', critical: '🔴',
  };

  const filesSection = result.files
    .filter(f => f.diagnostics.length > 0)
    .slice(0, 10)
    .map(f => `### \`${f.file}\`\n${f.diagnostics.map(d =>
      `- ${d.severity === 'error' ? '⛔' : d.severity === 'warning' ? '⚠️' : '💬'} L${d.line}: **${d.ruleName}** — ${d.message}`
    ).join('\n')}`)
    .join('\n\n');

  const body = `## Vali AI Code Quality Report

${gradeEmoji[score.grade] ?? '❓'} **AI Slop Score: ${score.score}/100** (${score.grade})

| Metric | Count |
|--------|-------|
| Files Scanned | ${summary.totalFiles} |
| Errors | ${summary.errorCount} |
| Warnings | ${summary.warningCount} |
| Info | ${summary.infoCount} |

${filesSection}

---
*Generated by [Vali](https://github.com/user/vali) v0.3.0*`;

  // 기존 vali 코멘트 검색
  const { data: comments } = await octokit.rest.issues.listComments({
    owner, repo, issue_number: prNumber,
  });
  const existing = comments.find(c => c.body?.includes('Vali AI Code Quality Report'));

  if (existing) {
    await octokit.rest.issues.updateComment({
      owner, repo, comment_id: existing.id, body,
    });
  } else {
    await octokit.rest.issues.createComment({
      owner, repo, issue_number: prNumber, body,
    });
  }
}
